export interface Food {
  id: number;
  img: string;
  price: number;
  name: string;
  favorite: boolean;
  star: number;
  tags: string[];
  cookTime?: number;
  origin: string;
}

export enum FoodTag {
  Breakfast = 'breakfast',
  Dinner = 'dinner',
  Lunch = 'lunch',
  Nutrious = 'nutrious',
  FastFood = 'fastFood',
  Cheap = 'cheap',
  Expensive = 'expensive',
}
export const foodTags = [
  FoodTag.Breakfast,
  FoodTag.Dinner,
  FoodTag.Lunch,
  FoodTag.Nutrious,
  FoodTag.FastFood,
  FoodTag.Cheap,
  FoodTag.Expensive,
];
export const foodData: Food[] = [
  {
    id: 1,
    img: '/assets/img (1).jpg',
    price: 10,
    name: 'Sambhar',
    favorite: true,
    star: 4.5,
    tags: [FoodTag.Breakfast, FoodTag.Dinner, FoodTag.Nutrious, FoodTag.Cheap],
    cookTime: 30,
    origin: 'Việt Nam',
  },
  {
    id: 2,
    img: '/assets/img (2).jpg',
    price: 40,
    name: 'Vada',
    favorite: true,
    star: 3.5,
    tags: [FoodTag.Breakfast, FoodTag.Dinner, FoodTag.FastFood, FoodTag.Cheap],
    cookTime: 20,
    origin: 'Việt Nam',
  },
  {
    id: 3,
    img: '/assets/img (3).jpg',
    price: 10,
    name: 'Poori',
    favorite: true,
    star: 3.0,
    tags: [
      FoodTag.Lunch,
      FoodTag.Nutrious,
      FoodTag.FastFood,
      FoodTag.Expensive,
    ],
    cookTime: 25,
    origin: 'Việt Nam',
  },
  {
    id: 4,
    img: '/assets/img (4).jpg',
    price: 40,
    name: 'Sabji',
    favorite: true,
    star: 2.5,
    tags: [FoodTag.Dinner, FoodTag.Lunch, FoodTag.Nutrious, FoodTag.Cheap],
    cookTime: 55,
    origin: 'Việt Nam',
  },
  {
    id: 5,
    img: '/assets/img (5).jpg',
    price: 90,
    name: 'Chole Bhature',
    favorite: true,
    star: 4.5,
    tags: [
      FoodTag.Breakfast,
      FoodTag.Dinner,
      FoodTag.Nutrious,
      FoodTag.FastFood,
      FoodTag.Expensive,
    ],
    cookTime: 90,
    origin: 'Việt Nam',
  },
  {
    id: 6,
    img: '/assets/img (6).jpg',
    price: 100,
    name: 'Samose',
    favorite: true,
    star: 3.5,
    tags: [FoodTag.Breakfast, FoodTag.FastFood, FoodTag.Cheap],
    cookTime: 40,
    origin: 'Việt Nam',
  },
  {
    id: 7,
    img: '/assets/img (7).jpg',
    price: 80,
    name: 'Idli Dosa',
    favorite: true,
    star: 3.5,
    tags: [
      FoodTag.Breakfast,
      FoodTag.Nutrious,
      FoodTag.FastFood,
      FoodTag.Cheap,
    ],
    cookTime: 10,
    origin: 'Việt Nam',
  },
  {
    id: 8,
    img: '/assets/img (8).jpg',
    price: 90,
    name: 'Kaju Katli',
    favorite: true,
    star: 2.5,
    tags: [
      FoodTag.Breakfast,
      FoodTag.Lunch,
      FoodTag.FastFood,
      FoodTag.Expensive,
    ],
    cookTime: 25,
    origin: 'Việt Nam',
  },
  {
    id: 9,
    img: '/assets/img (9).jpg',
    price: 100,
    name: 'Bharta',
    favorite: true,
    star: 2.7,
    tags: [FoodTag.Breakfast, FoodTag.Lunch, FoodTag.FastFood, FoodTag.Cheap],
    cookTime: 90,
    origin: 'Việt Nam',
  },
  {
    id: 10,
    img: '/assets/img (10).jpg',
    price: 10,
    name: 'South Indian',
    favorite: true,
    star: 4.5,
    tags: [
      FoodTag.Breakfast,
      FoodTag.Nutrious,
      FoodTag.FastFood,
      FoodTag.Expensive,
    ],
    cookTime: 30,
    origin: 'Việt Nam',
  },
  {
    id: 11,
    img: '/assets/img (11).jpg',
    price: 80,
    name: 'Meethai',
    favorite: true,
    star: 3.4,
    tags: [
      FoodTag.Lunch,
      FoodTag.Nutrious,
      FoodTag.FastFood,
      FoodTag.Expensive,
    ],
    cookTime: 20,
    origin: 'Việt Nam',
  },
  {
    id: 12,
    img: '/assets/img (12).jpg',
    price: 20,
    name: 'Butter Chicken',
    favorite: true,
    star: 2.5,
    tags: [FoodTag.Dinner, FoodTag.FastFood, FoodTag.Expensive],
    cookTime: 29,
    origin: 'Việt Nam',
  },
];
